sudo: false
language: node_js
node_js:
  - "7"

before_install:
  - pip install --user awscli
  - chmod +x tools/build/s3_cleanup.sh

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn build

after_success:
  - yarn codecov

before_deploy:
  - ./tools/build/s3_cleanup.sh

deploy:
  - provider: s3
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: ventured.one
    region: $AWS_S3_REGION
    skip_cleanup: true
    local_dir: dist
    cache_control: "max-age=21600"
  - provider: s3
    on:
      branch: develop
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: develop.ventured.one
    region: $AWS_S3_REGION
    skip_cleanup: true
    local_dir: dist
    cache_control: "max-age=21600"

